Example 1: AI vs ML vs DL (Simple Illustration)


In [ ]:
# AI vs ML vs DL simple example (conceptual print)

print("Artificial Intelligence (AI): Machines that mimic human intelligence")
print("Machine Learning (ML): AI that learns from data")
print("Deep Learning (DL): ML using neural networks")

print("\nRelationship:")
print("AI -> ML -> DL")

Artificial Intelligence (AI): Machines that mimic human intelligence
Machine Learning (ML): AI that learns from data
Deep Learning (DL): ML using neural networks

Relationship:
AI -> ML -> DL


Example 2: Python Variables

In [ ]:
name = "AI Student"
age = 26
height = 1.75

print(name)

AI Student


Example 3: Data Types Check

In [ ]:
x = 10
y = 3.14
z = "Hello"

print(type(x))

<class 'int'>


Example 4: List Operations

In [ ]:
numbers = [1, 2, 3, 4, 5]

print("List:", numbers)
print("Sum:", sum(numbers))
print("Max:", max(numbers))
print("Min:", min(numbers))

List: [1, 2, 3, 4, 5]
Sum: 15
Max: 5
Min: 1


Example 5: Loop Example

In [ ]:
for i in range(1, 6):
    print("Number:", i)

Number: 1
Number: 2
Number: 3
Number: 4
Number: 5


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# New section

# New section

Example 6: Function Example

In [ ]:
def square(x):
    return x * x

print(square(10))

100


Example 7: NumPy Array Creation

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Example 8: NumPy Math Operations

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

Sum: 100
Mean: 25.0
Max: 40
Min: 10


Example 9: 2D NumPy Array

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


Example 10: Reshaping Array

In [ ]:
import numpy as np

arr = np.arange(1, 7)

reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


=========================

📘 ASSIGNMENTS in-class

=========================

Assignment 1: Python Basics

In [ ]:
# 1. Create variables: name, age, country
# 2. Print them
# 3. Print their data types

AI Student
26
USA
<class 'str'>
<class 'int'>
<class 'str'>


Assignment 2: Lists & Loops

In [ ]:
# 1. Create a list of 10 numbers
# 2. Print all numbers using a loop
# 3. Find sum and average

1
2
3
4
5
6
7
8
9
10
Sum: 55
Average: 5.5


Assignment 3: Functions

In [ ]:
# 1. Create a function that returns cube of a number
# 2. Test it with 3 different values

8
27
64


Assignment 4: NumPy Practice

In [ ]:
# 1. Create a NumPy array of 10 numbers
# 2. Find mean, sum, max, min
# 3. Reshape into 2x5 matrix

Sum: 55
Mean: 5.5
Max: 10
Min: 1
Reshaped array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
